services:

  fastapi_app:

    build: .

    container_name: fastapi_support_assistant

    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

    restart: always

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      QDRANT_HOST: qdrant_db
      QDRANT_PORT: 6333
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres_db:5432/${POSTGRES_DB:-servicenow_ai}

    volumes:
      - .:/app

    depends_on:
      postgres_db:
        condition: service_healthy

      qdrant_db:
        condition: service_started

    networks:
      - app_network


  postgres_db:

    image: postgres:15-alpine

    container_name: postgres_relational_db

    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-servicenow_ai}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-servicenow_ai}" ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - app_network

volumes:

  qdrant_storage:

  postgres_data:

networks:

  app_network:

    driver: bridge
